PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS temperatur (
	"id"	INTEGER,
	"box"	INTEGER NOT NULL,
	"time"	INTEGER NOT NULL,
	"value"	REAL NOT NULL,
	"dtime" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS humidity (
	"id"	INTEGER,
	"box"	INTEGER NOT NULL,
        "inner" INTEGER NOT NULL,
	"time"	INTEGER NOT NULL,
	"value"	REAL NOT NULL,
    	"dtime" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY("id" AUTOINCREMENT)
);
